"""empty message

Revision ID: 109fafe841a3
Revises: 5dde5207e310
Create Date: 2021-07-02 18:21:13.448267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '109fafe841a3'
down_revision = '5dde5207e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('async')
    op.drop_index('poems_id_uindex', table_name='poems')
    op.drop_table('poems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='poems_pk')
    )
    op.create_index('poems_id_uindex', 'poems', ['id'], unique=False)
    op.create_table('async',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='async_pk')
    )
    # ### end Alembic commands ###
