"""empty message

Revision ID: ec85b60dc58b
Revises: 
Create Date: 2021-05-05 02:21:16.572769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec85b60dc58b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en', sa.String(length=25), nullable=False),
    sa.Column('translation', sa.String(length=25), nullable=True),
    sa.Column('ru', sa.String(length=25), nullable=False),
    sa.Column('repeat_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en'),
    sa.UniqueConstraint('en'),
    sa.UniqueConstraint('ru'),
    sa.UniqueConstraint('ru'),
    sa.UniqueConstraint('translation'),
    sa.UniqueConstraint('translation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translate')
    # ### end Alembic commands ###
