"""empty message

Revision ID: f92eba433058
Revises: 670761818108
Create Date: 2021-05-21 23:41:58.586538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92eba433058'
down_revision = '670761818108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('lyrics', sa.Text(), nullable=True))
    op.drop_column('song', 'lirics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('lirics', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('song', 'lyrics')
    # ### end Alembic commands ###
